// A list of all actions in the system.
export default {
  LOGIN_ATTEMPT: 'LOGIN_ATTEMPT',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  STARTUP: 'STARTUP',
  TEMPERATURE_REQUEST: 'TEMPERATURE_REQUEST',
  TEMPERATURE_RECEIVE: 'TEMPERATURE_RECEIVE',
  TEMPERATURE_FAILURE: 'TEMPERATURE_FAILURE'
}
